# Generated by Django 2.0.1 on 2018-01-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
